language: php
dist: xenial
php:
 - 7.0
script: 
 - phpunit Test.php
# Customize when the notification emails are sent.
notifications:
 email:
 - isamaleo@espol.edu.ec
 on_success: never
 on_failure: always
