language: php

dist: xenial 

php:
- 7.0

env:
- BD=pgsql

before_install:
- sudo apt-get update -q
- sudo apt-get install apache2 -y

install: ./install-dependencies.sh

before_script: true

script: 
- phpunit Test.php

notifications:
 email:
 - isamaleo@espol.edu.ec
 on_success: never
 on_failure: always
